# vim: ft=ruby:

app_identifier ENV["BUNDLE_IDENTIFIER"]
username "dan@dlo.me" # your Apple ID user

force true
skip_screenshots true
skip_metadata true
submit_for_review ENV['SUBMIT_FOR_REVIEW']
project_file = "Notchy.xcodeproj"

app_review_information(
  first_name: "Dan",
  last_name: "Loewenherz",
  phone_number: "786-201-1161",
  email_address: "dan@lionheartsw.com",
)

