# vim: ft=ruby:

app_identifier "com.lionheartsw.NotchyLovesAppReview" # The bundle identifier of your app
username "dan@lionheartsw.com" # your Apple ID user

skip_screenshots true
force true
skip_metadata true
project_file = "Notchy.xcodeproj"

app_review_information(
  first_name: "Dan",
  last_name: "Loewenherz",
  phone_number: "786-201-1161",
  email_address: "dan@lionheartsw.com",
  demo_user: "",
  demo_password: ""
)

