# vim: ft=ruby:

app_identifier ENV["BUNDLE_IDENTIFIER"]
username "dan@dlo.me" # your Apple ID user

# skip_screenshots true
force true
# skip_metadata true
submit_for_review true
project_file = "Notchy.xcodeproj"

app_review_information(
  first_name: "Dan",
  last_name: "Loewenherz",
  phone_number: "786-201-1161",
  email_address: "dan@lionheartsw.com",
  demo_user: "",
  demo_password: ""
)

